environment: development
port: 
  grpc: 8090
  restApi: 8091
log:
  level: trace # trace,debug,info,warn,error,fatal,panic
  folder: .log
  format: json
mysql:
  host: localhost
  port: 3306
  user: root
  password: new-password
  db: rainbowtest
redis:
  host: localhost
  port: 6379
  password: ""
wechatPay:
  #url: https://app-test.web3verse.space/conflux-pay/v0
  url: http://127.0.0.1:8082/v0
fee:
  userDefaultArrearsQuota: 0
  userDefaultFreeOtherAPIQuota: 5000
  userDefaultFreeMintQuota: 100
  userDefaultFreeDeployQuota: 5
cfxPrice: 0.8 # unit 元
schedules:
  mergeFiatlog: "@daily"