// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: settle.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SettleClient is the client API for Settle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettleClient interface {
	Deposite(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*WxOrder, error)
	GetWxOrder(ctx context.Context, in *WxOrderRequest, opts ...grpc.CallOption) (*WxOrder, error)
	BuyGas(ctx context.Context, in *BuySponsorRequest, opts ...grpc.CallOption) (*Empty, error)
	BuyStorage(ctx context.Context, in *BuySponsorRequest, opts ...grpc.CallOption) (*Empty, error)
	RefundSponsor(ctx context.Context, in *RefundSponsorRequest, opts ...grpc.CallOption) (*Empty, error)
	RefundApiFee(ctx context.Context, in *RefundApiFeeRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserBalance(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserBalance, error)
	GetUserApiQuota(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserApiQuotas, error)
	CreateCmcDepositNo(ctx context.Context, in *CreateCmcDepositNoReqeust, opts ...grpc.CallOption) (*Empty, error)
	QueryRecentCmbHistory(ctx context.Context, in *Pagenation, opts ...grpc.CallOption) (*QueryRecentCmbHistoryResponse, error)
	UpdateCmcDepositNoRelation(ctx context.Context, in *UpdateCmcDepositNoRelationRequest, opts ...grpc.CallOption) (*Empty, error)
}

type settleClient struct {
	cc grpc.ClientConnInterface
}

func NewSettleClient(cc grpc.ClientConnInterface) SettleClient {
	return &settleClient{cc}
}

func (c *settleClient) Deposite(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*WxOrder, error) {
	out := new(WxOrder)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/Deposite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) GetWxOrder(ctx context.Context, in *WxOrderRequest, opts ...grpc.CallOption) (*WxOrder, error) {
	out := new(WxOrder)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/GetWxOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) BuyGas(ctx context.Context, in *BuySponsorRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/BuyGas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) BuyStorage(ctx context.Context, in *BuySponsorRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/BuyStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) RefundSponsor(ctx context.Context, in *RefundSponsorRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/RefundSponsor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) RefundApiFee(ctx context.Context, in *RefundApiFeeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/RefundApiFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) GetUserBalance(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserBalance, error) {
	out := new(UserBalance)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/GetUserBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) GetUserApiQuota(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserApiQuotas, error) {
	out := new(UserApiQuotas)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/GetUserApiQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) CreateCmcDepositNo(ctx context.Context, in *CreateCmcDepositNoReqeust, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/CreateCmcDepositNo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) QueryRecentCmbHistory(ctx context.Context, in *Pagenation, opts ...grpc.CallOption) (*QueryRecentCmbHistoryResponse, error) {
	out := new(QueryRecentCmbHistoryResponse)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/QueryRecentCmbHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleClient) UpdateCmcDepositNoRelation(ctx context.Context, in *UpdateCmcDepositNoRelationRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rainbowsettle.Settle/UpdateCmcDepositNoRelation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettleServer is the server API for Settle service.
// All implementations must embed UnimplementedSettleServer
// for forward compatibility
type SettleServer interface {
	Deposite(context.Context, *DepositRequest) (*WxOrder, error)
	GetWxOrder(context.Context, *WxOrderRequest) (*WxOrder, error)
	BuyGas(context.Context, *BuySponsorRequest) (*Empty, error)
	BuyStorage(context.Context, *BuySponsorRequest) (*Empty, error)
	RefundSponsor(context.Context, *RefundSponsorRequest) (*Empty, error)
	RefundApiFee(context.Context, *RefundApiFeeRequest) (*Empty, error)
	GetUserBalance(context.Context, *UserID) (*UserBalance, error)
	GetUserApiQuota(context.Context, *UserID) (*UserApiQuotas, error)
	CreateCmcDepositNo(context.Context, *CreateCmcDepositNoReqeust) (*Empty, error)
	QueryRecentCmbHistory(context.Context, *Pagenation) (*QueryRecentCmbHistoryResponse, error)
	UpdateCmcDepositNoRelation(context.Context, *UpdateCmcDepositNoRelationRequest) (*Empty, error)
	mustEmbedUnimplementedSettleServer()
}

// UnimplementedSettleServer must be embedded to have forward compatible implementations.
type UnimplementedSettleServer struct {
}

func (UnimplementedSettleServer) Deposite(context.Context, *DepositRequest) (*WxOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposite not implemented")
}
func (UnimplementedSettleServer) GetWxOrder(context.Context, *WxOrderRequest) (*WxOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWxOrder not implemented")
}
func (UnimplementedSettleServer) BuyGas(context.Context, *BuySponsorRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyGas not implemented")
}
func (UnimplementedSettleServer) BuyStorage(context.Context, *BuySponsorRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyStorage not implemented")
}
func (UnimplementedSettleServer) RefundSponsor(context.Context, *RefundSponsorRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundSponsor not implemented")
}
func (UnimplementedSettleServer) RefundApiFee(context.Context, *RefundApiFeeRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundApiFee not implemented")
}
func (UnimplementedSettleServer) GetUserBalance(context.Context, *UserID) (*UserBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBalance not implemented")
}
func (UnimplementedSettleServer) GetUserApiQuota(context.Context, *UserID) (*UserApiQuotas, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserApiQuota not implemented")
}
func (UnimplementedSettleServer) CreateCmcDepositNo(context.Context, *CreateCmcDepositNoReqeust) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCmcDepositNo not implemented")
}
func (UnimplementedSettleServer) QueryRecentCmbHistory(context.Context, *Pagenation) (*QueryRecentCmbHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRecentCmbHistory not implemented")
}
func (UnimplementedSettleServer) UpdateCmcDepositNoRelation(context.Context, *UpdateCmcDepositNoRelationRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCmcDepositNoRelation not implemented")
}
func (UnimplementedSettleServer) mustEmbedUnimplementedSettleServer() {}

// UnsafeSettleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettleServer will
// result in compilation errors.
type UnsafeSettleServer interface {
	mustEmbedUnimplementedSettleServer()
}

func RegisterSettleServer(s grpc.ServiceRegistrar, srv SettleServer) {
	s.RegisterService(&Settle_ServiceDesc, srv)
}

func _Settle_Deposite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).Deposite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/Deposite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).Deposite(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_GetWxOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WxOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).GetWxOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/GetWxOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).GetWxOrder(ctx, req.(*WxOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_BuyGas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuySponsorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).BuyGas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/BuyGas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).BuyGas(ctx, req.(*BuySponsorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_BuyStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuySponsorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).BuyStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/BuyStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).BuyStorage(ctx, req.(*BuySponsorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_RefundSponsor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundSponsorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).RefundSponsor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/RefundSponsor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).RefundSponsor(ctx, req.(*RefundSponsorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_RefundApiFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundApiFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).RefundApiFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/RefundApiFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).RefundApiFee(ctx, req.(*RefundApiFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_GetUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).GetUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/GetUserBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).GetUserBalance(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_GetUserApiQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).GetUserApiQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/GetUserApiQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).GetUserApiQuota(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_CreateCmcDepositNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCmcDepositNoReqeust)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).CreateCmcDepositNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/CreateCmcDepositNo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).CreateCmcDepositNo(ctx, req.(*CreateCmcDepositNoReqeust))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_QueryRecentCmbHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagenation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).QueryRecentCmbHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/QueryRecentCmbHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).QueryRecentCmbHistory(ctx, req.(*Pagenation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settle_UpdateCmcDepositNoRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCmcDepositNoRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleServer).UpdateCmcDepositNoRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rainbowsettle.Settle/UpdateCmcDepositNoRelation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleServer).UpdateCmcDepositNoRelation(ctx, req.(*UpdateCmcDepositNoRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Settle_ServiceDesc is the grpc.ServiceDesc for Settle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Settle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rainbowsettle.Settle",
	HandlerType: (*SettleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deposite",
			Handler:    _Settle_Deposite_Handler,
		},
		{
			MethodName: "GetWxOrder",
			Handler:    _Settle_GetWxOrder_Handler,
		},
		{
			MethodName: "BuyGas",
			Handler:    _Settle_BuyGas_Handler,
		},
		{
			MethodName: "BuyStorage",
			Handler:    _Settle_BuyStorage_Handler,
		},
		{
			MethodName: "RefundSponsor",
			Handler:    _Settle_RefundSponsor_Handler,
		},
		{
			MethodName: "RefundApiFee",
			Handler:    _Settle_RefundApiFee_Handler,
		},
		{
			MethodName: "GetUserBalance",
			Handler:    _Settle_GetUserBalance_Handler,
		},
		{
			MethodName: "GetUserApiQuota",
			Handler:    _Settle_GetUserApiQuota_Handler,
		},
		{
			MethodName: "CreateCmcDepositNo",
			Handler:    _Settle_CreateCmcDepositNo_Handler,
		},
		{
			MethodName: "QueryRecentCmbHistory",
			Handler:    _Settle_QueryRecentCmbHistory_Handler,
		},
		{
			MethodName: "UpdateCmcDepositNoRelation",
			Handler:    _Settle_UpdateCmcDepositNoRelation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settle.proto",
}
